SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [etl].[vw_src_TI_PD_PATRON]
AS
	SELECT *
		, HASHBYTES('sha2_256', ISNULL(RTRIM(CONVERT(varchar(25),BIRTH_DATE1)),'DBNULL_DATETIME') + ISNULL(RTRIM(CONVERT(varchar(25),BIRTH_DATE2)),'DBNULL_DATETIME') + ISNULL(RTRIM(BIRTH_PLACE1),'DBNULL_TEXT') + ISNULL(RTRIM(BIRTH_PLACE2),'DBNULL_TEXT') + ISNULL(RTRIM(CONVERT(varchar(25),ENTRY_DATETIME)),'DBNULL_DATETIME') + ISNULL(RTRIM(ENTRY_USER),'DBNULL_TEXT') + ISNULL(RTRIM(ETHNIC1),'DBNULL_TEXT') + ISNULL(RTRIM(ETHNIC2),'DBNULL_TEXT') + ISNULL(RTRIM(ETLSID),'DBNULL_TEXT') + ISNULL(RTRIM(EV_EMAIL),'DBNULL_TEXT') + ISNULL(RTRIM(CONVERT(varchar(25),EXPORT_DATETIME)),'DBNULL_DATETIME') + ISNULL(RTRIM(EXTERNAL_NUMBER),'DBNULL_TEXT') + ISNULL(RTRIM(GENDER1),'DBNULL_TEXT') + ISNULL(RTRIM(GENDER2),'DBNULL_TEXT') + ISNULL(RTRIM(HOUSEHOLD_INCOME),'DBNULL_TEXT') + ISNULL(RTRIM(INTERNET_PROFILE),'DBNULL_TEXT') + ISNULL(RTRIM(CONVERT(varchar(25),LAST_DATETIME)),'DBNULL_DATETIME') + ISNULL(RTRIM(LAST_USER),'DBNULL_TEXT') + ISNULL(RTRIM(MAGSTRIPE_ID),'DBNULL_TEXT') + ISNULL(RTRIM(MAIDEN1),'DBNULL_TEXT') + ISNULL(RTRIM(MAIDEN2),'DBNULL_TEXT') + ISNULL(RTRIM(MAIL_NAME),'DBNULL_TEXT') + ISNULL(RTRIM(MARITAL_STATUS),'DBNULL_TEXT') + ISNULL(RTRIM(NAME),'DBNULL_TEXT') + ISNULL(RTRIM(NAME2),'DBNULL_TEXT') + ISNULL(RTRIM(NICKNAME1),'DBNULL_TEXT') + ISNULL(RTRIM(NICKNAME2),'DBNULL_TEXT') + ISNULL(RTRIM(PATRON),'DBNULL_TEXT') + ISNULL(RTRIM(RELEASE),'DBNULL_TEXT') + ISNULL(RTRIM(RELIGION1),'DBNULL_TEXT') + ISNULL(RTRIM(RELIGION2),'DBNULL_TEXT') + ISNULL(RTRIM(SOURCE),'DBNULL_TEXT') + ISNULL(RTRIM(SOURCE_ID),'DBNULL_TEXT') + ISNULL(RTRIM(STATUS),'DBNULL_TEXT') + ISNULL(RTRIM(SUFFIX),'DBNULL_TEXT') + ISNULL(RTRIM(SUFFIX2),'DBNULL_TEXT') + ISNULL(RTRIM(TITLE),'DBNULL_TEXT') + ISNULL(RTRIM(TITLE2),'DBNULL_TEXT') + ISNULL(RTRIM(VIP),'DBNULL_TEXT') + ISNULL(RTRIM(ZID),'DBNULL_TEXT')) AS ETL_DeltaHashKey
	FROM src.TI_PD_PATRON
GO
