SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [pac12].[vw_DimPriceCode] as 
(
	SELECT  [DimPriceCodeId], [ETL__SourceSystem], [ETL__CreatedDate], [ETL__UpdatedDate], [ETL__IsDeleted], [ETL__DeltaHashKey], [ETL__SSID], [ETL__SSID_TM_event_id], [ETL__SSID_TM_price_code], [Season], [Item], [PriceCode], [PriceCodeName], [PriceCodeDesc], [PriceCodeClass], [PC1], [PC2], [PC3], [PC4], [PriceCodeGroup], [FullPrice], [Config_Category1], [Config_Category2], [Config_Category3], [Config_Category4], [Config_Category5], [Config_TicketTypeCode], [CreatedBy], [UpdatedBy], [CreatedDate], [UpdatedDate], [Custom_Int_1], [Custom_Int_2], [Custom_Int_3], [Custom_Int_4], [Custom_Int_5], [Custom_Dec_1], [Custom_Dec_2], [Custom_Dec_3], [Custom_Dec_4], [Custom_Dec_5], [Custom_DateTime_1], [Custom_DateTime_2], [Custom_DateTime_3], [Custom_DateTime_4], [Custom_DateTime_5], [Custom_Bit_1], [Custom_Bit_2], [Custom_Bit_3], [Custom_Bit_4], [Custom_Bit_5], [Custom_nVarChar_1], [Custom_nVarChar_2], [Custom_nVarChar_3], [Custom_nVarChar_4], [Custom_nVarChar_5], [TM_price], [TM_parent_price_code], [TM_ticket_type_code], [TM_full_price_ticket_type_code], [TM_tt_code], [TM_ticket_type], [TM_ticket_type_desc], [TM_ticket_type_category], [TM_comp_ind], [TM_default_host_offer_id], [TM_ticket_type_relationship], [TM_upd_user], [TM_upd_datetime], [TM_pricing_method], [TM_host_price_level], [TM_host_ticket_type], [TM_ticket_template_override], [TM_ticket_template], [TM_code], [TM_price_code_group], [TM_price_code_desc], [TM_price_code_info1], [TM_price_code_info2], [TM_price_code_info3], [TM_price_code_info4], [TM_price_code_info5], [TM_color], [TM_printed_price], [TM_pc_ticket], [TM_pc_tax], [TM_pc_licfee], [TM_pc_other1], [TM_pc_other2], [TM_tax_rate_a], [TM_tax_rate_b], [TM_tax_rate_c], [TM_onsale_datetime], [TM_offsale_datetime], [TM_inet_onsale_datetime], [TM_inet_offsale_datetime], [TM_inet_price_code_name], [TM_inet_offer_text], [TM_inet_full_price], [TM_inet_min_tickets_per_tran], [TM_inet_max_tickets_per_tran], [TM_tid_family_id], [TM_on_purch_add_to_acct_group_id], [TM_auto_add_membership_name], [TM_required_membership_list], [TM_card_template_override], [TM_card_template], [TM_ledger_id], [TM_merchant_id], [TM_merchant_code], [TM_merchant_color], [TM_membership_reqd_for_purchase], [TM_membership_id_for_membership_event], [TM_membership_name], [TM_membership_expiration_date], [TM_club_group_enabled]
	FROM dbo.DimPriceCode_V2 (NOLOCK)
)
GO
