SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [preods].[TM_CustomerUpdate_BeforeUpdates]
AS

SELECT DISTINCT
	CONVERT(NVARCHAR(100),[ETL__multi_query_value_for_audit]) [multi_query_value_for_audit_K]
	,CONVERT(INT,[AccountId]) [AccountId_K]
	,CONVERT(NVARCHAR(25),[Errors_ApiSqlCode]) [Errors_ApiSqlCode]
	,CONVERT(NVARCHAR(25),[Errors_BeforeUpdate]) [Errors_BeforeUpdate]
	,CONVERT(INT,Coalesce([BeforeUpdate_acct_id],[L4_AllData_BeforeUpdate_command1_customer_acct_id])) [acct_id]
	,CONVERT(INT,Coalesce([BeforeUpdate_cust_name_id],[L4_AllData_BeforeUpdate_command1_customer_cust_name_id])) [cust_name_id]
	,CONVERT(NVARCHAR(25),Coalesce([BeforeUpdate_rec_status], [L3_AllData_BeforeUpdate_command1_rec_status])) [rec_status]
	,CONVERT(NVARCHAR(50),Coalesce([BeforeUpdate_acct_type],[L4_AllData_BeforeUpdate_command1_customer_acct_type])) [acct_type]
	,CONVERT(NVARCHAR(255),Coalesce([BeforeUpdate_company_name],[L4_AllData_BeforeUpdate_command1_customer_company_name])) [company_name]
	,CONVERT(NVARCHAR(100),Coalesce([BeforeUpdate_name_first], [L4_AllData_BeforeUpdate_command1_customer_name_first])) [name_first]
	,CONVERT(NVARCHAR(100),Coalesce([BeforeUpdate_name_mi], [L4_AllData_BeforeUpdate_command1_customer_name_mi])) [name_mi]
	,CONVERT(NVARCHAR(100),Coalesce([BeforeUpdate_name_last],[L4_AllData_BeforeUpdate_command1_customer_name_last])) [name_last]
	,CONVERT(NVARCHAR(100),Coalesce([BeforeUpdate_title], [L4_AllData_BeforeUpdate_command1_customer_title])) [title]
	,CONVERT(NVARCHAR(100),Coalesce([BeforeUpdate_street_addr_1],[L4_AllData_BeforeUpdate_command1_customer_street_addr_1])) [street_addr_1]
	,CONVERT(NVARCHAR(100),Coalesce([BeforeUpdate_street_addr_2],[L4_AllData_BeforeUpdate_command1_customer_street_addr_2])) [street_addr_2]
	,CONVERT(NVARCHAR(50),Coalesce([BeforeUpdate_city],[L4_AllData_BeforeUpdate_command1_customer_city])) [city]
	,CONVERT(NVARCHAR(25),Coalesce([BeforeUpdate_state],[L4_AllData_BeforeUpdate_command1_customer_state])) [state]
	,CONVERT(NVARCHAR(25),Coalesce([BeforeUpdate_zip],[L4_AllData_BeforeUpdate_command1_customer_zip])) [zip]
	,CONVERT(NVARCHAR(25),Coalesce([BeforeUpdate_country], [L4_AllData_BeforeUpdate_command1_customer_country])) [country]
	,CONVERT(NVARCHAR(100),Coalesce([BeforeUpdate_phone_day],[L4_AllData_BeforeUpdate_command1_customer_phone_day])) [phone_day]
	,CONVERT(NVARCHAR(25),Coalesce([BeforeUpdate_phone_eve],[L4_AllData_BeforeUpdate_command1_customer_phone_eve])) [phone_eve]
    ,CONVERT(NVARCHAR(100),Coalesce([BeforeUpdate_phone_fax],[L4_AllData_BeforeUpdate_command1_customer_phone_fax])) [phone_fax]
	,CONVERT(NVARCHAR(100),Coalesce([BeforeUpdate_phone_cell],[L4_AllData_BeforeUpdate_command1_customer_phone_cell])) [phone_cell]
	,CONVERT(INT,Coalesce([BeforeUpdate_priority],[L3_AllData_BeforeUpdate_command1_priority])) [priority]
	,CONVERT(DECIMAL(18,2),Coalesce([BeforeUpdate_points_YTD],[L4_AllData_BeforeUpdate_command1_customer_points_YTD])) [points_YTD]
	,CONVERT(DECIMAL(18,2),Coalesce([BeforeUpdate_points_ITD],[L4_AllData_BeforeUpdate_command1_customer_points_ITD])) [points_ITD]
	,CONVERT(NVARCHAR(100),Coalesce([BeforeUpdate_email],[L4_AllData_BeforeUpdate_command1_customer_email])) [email]
	,CONVERT(DATE,Coalesce([BeforeUpdate_add_date],[L4_AllData_BeforeUpdate_command1_customer_add_date])) [add_date]
	,CONVERT(NVARCHAR(25),Coalesce([BeforeUpdate_name_type],[L4_AllData_BeforeUpdate_command1_customer_name_type])) [name_type]
	,CONVERT(NVARCHAR(250),Coalesce([BeforeUpdate_owner_name],[L4_AllData_BeforeUpdate_command1_customer_owner_name])) [owner_name]
	,CONVERT(DATE,Coalesce([BeforeUpdate_birth_date],[L4_AllData_BeforeUpdate_command1_customer_birth_date])) [birth_date]
	,CONVERT(NVARCHAR(10),Coalesce([BeforeUpdate_gender],[L4_AllData_BeforeUpdate_command1_customer_gender])) [gender]
	,CONVERT(NVARCHAR(100),Coalesce([BeforeUpdate_other_info_1],[L3_AllData_BeforeUpdate_command1_other_info_1])) [other_info_1]
	,CONVERT(NVARCHAR(100),Coalesce([BeforeUpdate_other_info_2],[L3_AllData_BeforeUpdate_command1_other_info_2])) [other_info_2]
	,CONVERT(NVARCHAR(100),Coalesce([BeforeUpdate_other_info_3],[L3_AllData_BeforeUpdate_command1_other_info_3])) [other_info_3]
	,CONVERT(NVARCHAR(100),Coalesce([BeforeUpdate_other_info_4],[L3_AllData_BeforeUpdate_command1_other_info_4])) [other_info_4]
	,CONVERT(NVARCHAR(100),Coalesce([BeforeUpdate_other_info_5],[L3_AllData_BeforeUpdate_command1_other_info_5])) [other_info_5]
	,CONVERT(NVARCHAR(100),Coalesce([BeforeUpdate_other_info_6],[L3_AllData_BeforeUpdate_command1_other_info_6])) [other_info_6]
	,CONVERT(NVARCHAR(100),Coalesce([BeforeUpdate_other_info_7],[L3_AllData_BeforeUpdate_command1_other_info_7])) [other_info_7]
	,CONVERT(NVARCHAR(100),Coalesce([BeforeUpdate_other_info_8],[L3_AllData_BeforeUpdate_command1_other_info_8])) [other_info_8]
	,CONVERT(NVARCHAR(100),Coalesce([BeforeUpdate_other_info_9],[L3_AllData_BeforeUpdate_command1_other_info_9])) [other_info_9]
	,CONVERT(NVARCHAR(100),Coalesce([BeforeUpdate_other_info_10],[L3_AllData_BeforeUpdate_command1_other_info_10])) [other_info_10]
	,CONVERT(INT,Coalesce([BeforeUpdate_rank],[L3_AllData_BeforeUpdate_command1_rank])) [rank]
	,CONVERT(NVARCHAR(25),Coalesce([BeforeUpdate_text_on_mobile_phone],[L4_AllData_BeforeUpdate_command1_customer_text_on_mobile_phone])) [text_on_mobile_phone]
	,CONVERT(DECIMAL(18,2),Coalesce([BeforeUpdate_total_donation_amount],[L4_AllData_BeforeUpdate_command1_customer_total_donation_amount])) [total_donation_amount]
	,CONVERT(DECIMAL(18,2),Coalesce([BeforeUpdate_ITD_donations],[L4_AllData_BeforeUpdate_command1_customer_ITD_donations])) [ITD_donations]
	,CONVERT(NVARCHAR(25),Coalesce([BeforeUpdate_honorary_donor],[L4_AllData_BeforeUpdate_command1_customer_honorary_donor])) [honorary_donor]
	,CONVERT(NVARCHAR(25),Coalesce([BeforeUpdate_acct_access_level],[L4_AllData_BeforeUpdate_command1_customer_acct_access_level])) [acct_access_level]
	,CONVERT(DECIMAL(18,2),Coalesce([BeforeUpdate_qualified_donation_amount],[L4_AllData_BeforeUpdate_command1_customer_qualified_donation_amount])) [qualified_donation_amount]
	,CONVERT(NVARCHAR(25),Coalesce([BeforeUpdate_phone_day_do_not_solicit],[L4_AllData_BeforeUpdate_command1_customer_phone_day_do_not_solicit])) [phone_day_do_not_solicit]
	,CONVERT(NVARCHAR(25),Coalesce([BeforeUpdate_phone_eve_do_not_solicit],[L4_AllData_BeforeUpdate_command1_customer_phone_eve_do_not_solicit])) [phone_eve_do_not_solicit]
	,CONVERT(NVARCHAR(25),Coalesce([BeforeUpdate_phone_cell_do_not_solicit],[L4_AllData_BeforeUpdate_command1_customer_phone_cell_do_not_solicit])) [phone_cell_do_not_solicit]
	,CONVERT(NVARCHAR(10),Coalesce([BeforeUpdate_phone_fax_do_not_solicit],[L4_AllData_BeforeUpdate_command1_customer_phone_fax_do_not_solicit])) [phone_fax_do_not_solicit]
	,CONVERT(NVARCHAR(25),Coalesce([BeforeUpdate_email_deliv_opt],[L4_AllData_BeforeUpdate_command1_customer_email_deliv_opt])) [email_deliv_opt]
	,CONVERT(NVARCHAR(25),Coalesce([BeforeUpdate_email_optout],[L4_AllData_BeforeUpdate_command1_customer_email_optout])) [email_optout]	
	,CONVERT(INT,Coalesce([BeforeUpdate_logon_attempts],[L3_AllData_BeforeUpdate_command1_logon_attempts])) [logon_attempts]
	,CONVERT(NVARCHAR(100),Coalesce([BeforeUpdate_result],[L3_AllData_BeforeUpdate_command1_result])) [result]
	,CONVERT(INT,Coalesce([BeforeUpdate_change_pin],[L3_AllData_BeforeUpdate_command1_change_pin])) [change_pin]
	,CONVERT(INT,Coalesce([BeforeUpdate_account_id_list], [L3_AllData_BeforeUpdate_command1_account_id_list])) [account_id_list]
	,CONVERT(NVARCHAR(25),Coalesce([BeforeUpdate_sql_code],[L3_AllData_BeforeUpdate_command1_sql_code])) [sql_code]
	,CONVERT(NVARCHAR(100),Coalesce([BeforeUpdate_cmd],[L3_AllData_BeforeUpdate_command1_cmd])) [cmd]

FROM [src].[TM_CustomerUpdate_Before] WITH (NOLOCK)
WHERE COALESCE([BeforeUpdate_acct_id],[L4_AllData_BeforeUpdate_command1_customer_acct_id]) IS NOT NULL
GO
