SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [preods].[TM_CustomerUpdate_After]
AS
SELECT DISTINCT
convert(nvarchar (100),[ETL__multi_query_value_for_audit]) [multi_query_value_for_audit_K]
,CONVERT(NVARCHAR(25),[AccountId]) [AccountId_K]
,CONVERT(int,					COALESCE([acct_id]							,[L4_AllData_AfterUpdate_command1_customer_acct_id]								)) [acct_id]
,CONVERT(int,					COALESCE([cust_name_id]						,[L4_AllData_AfterUpdate_command1_customer_cust_name_id]						)) [cust_name_id]
,CONVERT(NVARCHAR(25),			COALESCE([rec_status]						,[L3_AllData_AfterUpdate_command1_rec_status]									)) [rec_status]
,CONVERT(NVARCHAR(50),			COALESCE([acct_type]						,[L4_AllData_AfterUpdate_command1_customer_acct_type]							)) [acct_type]
,CONVERT(NVARCHAR(255),			COALESCE([company_name]						,[L4_AllData_AfterUpdate_command1_customer_company_name]						)) [company_name]
,CONVERT(NVARCHAR(100),			COALESCE([name_first]						,[L4_AllData_AfterUpdate_command1_customer_name_first]							)) [name_first]
,CONVERT(NVARCHAR(100),			COALESCE([name_mi]							,[L4_AllData_AfterUpdate_command1_customer_name_mi]								)) [name_mi]
,CONVERT(NVARCHAR(50),			COALESCE([name_last]						,[L4_AllData_AfterUpdate_command1_customer_name_last]							)) [name_last]
,CONVERT(NVARCHAR(100),			COALESCE([title]							,[L4_AllData_AfterUpdate_command1_customer_title]								)) [title]
,CONVERT(NVARCHAR(100),			COALESCE([street_addr_1]					,[L4_AllData_AfterUpdate_command1_customer_street_addr_1]						)) [street_addr_1]
,CONVERT(NVARCHAR(100),			COALESCE([street_addr_2]					,[L4_AllData_AfterUpdate_command1_customer_street_addr_2]						)) [street_addr_2]
,CONVERT(NVARCHAR(25),			COALESCE([city]								,[L4_AllData_AfterUpdate_command1_customer_city]								)) [city]
,CONVERT(NVARCHAR(25),			COALESCE([state]							,[L4_AllData_AfterUpdate_command1_customer_state]								)) [state]
,CONVERT(NVARCHAR(25),			COALESCE([zip]								,[L4_AllData_AfterUpdate_command1_customer_zip]									)) [zip]
,CONVERT(NVARCHAR(25),			COALESCE([country]							,[L4_AllData_AfterUpdate_command1_customer_country]								)) [country]
,CONVERT(NVARCHAR(25),			COALESCE([phone_day]						,[L4_AllData_AfterUpdate_command1_customer_phone_day]							)) [phone_day]
,CONVERT(NVARCHAR(25),			COALESCE([phone_eve]						,[L4_AllData_AfterUpdate_command1_customer_phone_eve]							)) [phone_eve]
,CONVERT(NVARCHAR(100),			COALESCE([phone_fax]						,[L4_AllData_AfterUpdate_command1_customer_phone_fax]							)) [phone_fax]
,CONVERT(NVARCHAR(100),			COALESCE([phone_cell]						,[L4_AllData_AfterUpdate_command1_customer_phone_cell]							)) [phone_cell]
,CONVERT(int,					COALESCE([priority]							,[L3_AllData_AfterUpdate_command1_priority]										)) [priority]
,CONVERT(decimal(18,2),			COALESCE([points_YTD]						,[L4_AllData_AfterUpdate_command1_customer_points_YTD]							)) [points_YTD]
,CONVERT(decimal(18,2),			COALESCE([points_ITD]						,[L4_AllData_AfterUpdate_command1_customer_points_ITD]							)) [points_ITD]
,CONVERT(NVARCHAR(100),			COALESCE([email]							,[L4_AllData_AfterUpdate_command1_customer_email]								)) [email]
,CONVERT(date,					COALESCE([add_date]							,[L4_AllData_AfterUpdate_command1_customer_add_date]							)) [add_date]
,CONVERT(NVARCHAR(25),			COALESCE([name_type]						,[L4_AllData_AfterUpdate_command1_customer_name_type]							)) [name_type]
,CONVERT(NVARCHAR(250),			COALESCE([owner_name]						,[L4_AllData_AfterUpdate_command1_customer_owner_name]							)) [owner_name]
,CONVERT(date,					COALESCE([birth_date]						,[L4_AllData_AfterUpdate_command1_customer_birth_date]							)) [birth_date]
,CONVERT(NVARCHAR(10),			COALESCE([gender]							,[L4_AllData_AfterUpdate_command1_customer_gender]								)) [gender]
,CONVERT(NVARCHAR(100),			COALESCE([other_info_1]						,[L3_AllData_AfterUpdate_command1_other_info_1]									)) [other_info_1]
,CONVERT(NVARCHAR(100),			COALESCE([other_info_2]						,[L3_AllData_AfterUpdate_command1_other_info_2]									)) [other_info_2]
,CONVERT(NVARCHAR(100),			COALESCE([other_info_3]						,[L3_AllData_AfterUpdate_command1_other_info_3]									)) [other_info_3]
,CONVERT(NVARCHAR(100),			COALESCE([other_info_4]						,[L3_AllData_AfterUpdate_command1_other_info_4]									)) [other_info_4]
,CONVERT(NVARCHAR(100),			COALESCE([other_info_5]						,[L3_AllData_AfterUpdate_command1_other_info_5]									)) [other_info_5]
,CONVERT(NVARCHAR(100),			COALESCE([other_info_6]						,[L3_AllData_AfterUpdate_command1_other_info_6]									)) [other_info_6]
,CONVERT(NVARCHAR(100),			COALESCE([other_info_7]						,[L3_AllData_AfterUpdate_command1_other_info_7]									)) [other_info_7]
,CONVERT(NVARCHAR(100),			COALESCE([other_info_8]						,[L3_AllData_AfterUpdate_command1_other_info_8]									)) [other_info_8]
,CONVERT(NVARCHAR(100),			COALESCE([other_info_9]						,[L3_AllData_AfterUpdate_command1_other_info_9]									)) [other_info_9]
,CONVERT(NVARCHAR(100),			COALESCE([other_info_10]					,[L3_AllData_AfterUpdate_command1_other_info_10]								)) [other_info_10]
,CONVERT(int,					COALESCE([rank]								,[L3_AllData_AfterUpdate_command1_rank]											)) [rank]
,CONVERT(NVARCHAR(25),			COALESCE([text_on_mobile_phone]				,[L4_AllData_AfterUpdate_command1_customer_text_on_mobile_phone]				)) [text_on_mobile_phone]
,CONVERT(decimal(18,2),			COALESCE([total_donation_amount]			,[L4_AllData_AfterUpdate_command1_customer_total_donation_amount]				)) [total_donation_amount]
,CONVERT(decimal(18,2),			COALESCE([ITD_donations]					,[L4_AllData_AfterUpdate_command1_customer_ITD_donations]						)) [ITD_donations]
,CONVERT(NVARCHAR(25),			COALESCE([honorary_donor]					,[L4_AllData_AfterUpdate_command1_customer_honorary_donor]						)) [honorary_donor]
,CONVERT(NVARCHAR(25),			COALESCE([acct_access_level]				,[L4_AllData_AfterUpdate_command1_customer_acct_access_level]					)) [acct_access_level]
,CONVERT(decimal(18,2),			COALESCE([qualified_donation_amount]		,[L4_AllData_AfterUpdate_command1_customer_qualified_donation_amount]			)) [qualified_donation_amount]
,CONVERT(NVARCHAR(25),			COALESCE([phone_day_do_not_solicit]			,[L4_AllData_AfterUpdate_command1_customer_phone_day_do_not_solicit]			)) [phone_day_do_not_solicit]
,CONVERT(NVARCHAR(25),			COALESCE([phone_eve_do_not_solicit]			,[L4_AllData_AfterUpdate_command1_customer_phone_eve_do_not_solicit]			)) [phone_eve_do_not_solicit]
,CONVERT(NVARCHAR(25),			COALESCE([phone_cell_do_not_solicit]		,[L4_AllData_AfterUpdate_command1_customer_phone_cell_do_not_solicit]			)) [phone_cell_do_not_solicit]
,CONVERT(NVARCHAR(10),			COALESCE([phone_fax_do_not_solicit]			,[L4_AllData_AfterUpdate_command1_customer_phone_fax_do_not_solicit]			)) [phone_fax_do_not_solicit]
,CONVERT(NVARCHAR(25),			COALESCE([email_deliv_opt]					,[L4_AllData_AfterUpdate_command1_customer_email_deliv_opt]						)) [email_deliv_opt]
,CONVERT(NVARCHAR(25),			COALESCE([email_optout]						,[L4_AllData_AfterUpdate_command1_customer_email_optout]						)) [email_optout]
,CONVERT(int,					COALESCE([logon_attempts]					,[L3_AllData_AfterUpdate_command1_logon_attempts]								)) [logon_attempts]
,CONVERT(NVARCHAR(100),			COALESCE([result]							,[L3_AllData_AfterUpdate_command1_result]										)) [result]
,CONVERT(int,					COALESCE([change_pin]						,[L3_AllData_AfterUpdate_command1_change_pin]									)) [change_pin]
,CONVERT(int,					COALESCE([account_id_list]					,[L3_AllData_AfterUpdate_command1_account_id_list]								)) [account_id_list]
,CONVERT(NVARCHAR(25),			COALESCE([sql_code]							,[L3_AllData_AfterUpdate_command1_sql_code]										)) [sql_code]
,CONVERT(NVARCHAR(100),			COALESCE([cmd]								,[L3_AllData_AfterUpdate_command1_cmd]											)) [cmd]			

FROM [src].[TM_CustomerUpdate_After] WITH (NOLOCK)
WHERE COALESCE([acct_id],[L4_AllData_AfterUpdate_command1_customer_acct_id]) is not null

GO
