SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [ro].[vwAdvance_GiftTransactionReview] 
AS
select DATE_OF_RECORD, CAMPAIGN_CODE, 
CASE WHEN TRANS_TYPE_DESC = 'Matching Gift' THEN CREDIT_AMOUNT
	 ELSE NET_LEGAL_AMOUNT END AS GIFT_CLUB_AMOUNT
,  TRANS_TYPE_DESC, ALLOC_DESC, PACIOLAN_ID, TX_NUMBER, dc.SSB_CRMSYSTEM_CONTACT_ID
from [dbo].[FD_SDA_TRANSACTION_DETAIL] don (NOLOCK)
INNER JOIN [dbo].[vwDimCustomer_ModAcctId] dc on dc.SourceSystem = 'Advance ASU' AND don.ID_NUMBER = dc.SSID
where 1=1
AND CASE WHEN TRANS_TYPE_DESC = 'Matching Gift' THEN CREDIT_AMOUNT
	 ELSE NET_LEGAL_AMOUNT END > 0



GO
