SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO












CREATE VIEW [segmentation].[vw__SDC_Gift_Clubs_DEV]

AS
(
SELECT  ssbid.SSB_CRMSYSTEM_CONTACT_ID
, gc.GIFT_CLUB_ID_NUMBER
, gc.GIFT_CLUB_CODE
, gc.GIFT_CLUB_DESC
, ISNULL(gc.QUALIFIED_AMOUNT,0) AS GIFT_CLUB_QUALIFIED_AMOUNT
, gc.GIFT_CLUB_YEAR
, gc.GIFT_CLUB_STATUS
, gc.DATE_ADDED AS GIFT_CLUB_DATE_ADDED
, gc.DATE_MODIFIED AS GIFT_CLUB_DATE_MODIFIED 
, ISNULL(x.SEATGIVING,0) AS SEATGIVING
, ISNULL(gc.QUALIFIED_AMOUNT,0) - ISNULL(x.SEATGIVING,0) AS PHILANTHROPIC_AMOUNT
FROM [dbo].[FD_SDC_GIFT_CLUBS] gc
	JOIN dbo.dimcustomerssbid ssbid ON ssbid.SSID = gc.GIFT_CLUB_ID_NUMBER
	LEFT JOIN ( SELECT DISTINCT ID_NUMBER
								,FISCAL_YEAR
								,SUM(NET_LEGAL_AMOUNT) OVER	(PARTITION BY PACIOLAN_ID,y.FISCAL_YEAR ) AS SEATGIVING	
				FROM (  SELECT  PACIOLAN_ID
								,trans.ID_NUMBER
								,CASE WHEN campaign_code LIKE 'SC%' THEN RIGHT(campaign_code,2) ELSE RIGHT(FISCAL_YEAR,2) END AS FISCAL_YEAR
								,NET_LEGAL_AMOUNT
						FROM    [dbo].[FD_SDA_TRANSACTION_DETAIL] trans 
						WHERE   (trans.CAMPAIGN_CODE LIKE 'SC%' OR trans.CAMPAIGN_CODE = '')
								AND ( ALLOC_DESC LIKE '%Seat Contribution%' OR ALLOC_DESC LIKE 'Suite%' )
								AND GYPMD_DESC LIKE '%Gift%'
								AND ISNULL(trans.PACIOLAN_ID,'')<>'')y
			  )x ON x.ID_NUMBER = gc.GIFT_CLUB_ID_NUMBER
					AND FISCAL_YEAR = RIGHT(gc.GIFT_CLUB_YEAR,2)
)





GO
