SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROC [dbo].[rptCust_ListBuild_FundOptions]
AS
SELECT DISTINCT ISNULL(ATHLETIC_FUND_DESC,'Blank/Missing') AS ATHLETIC_FUND_DESC FROM dbo.FD_SDA_TRANSACTION_DETAIL

GO
