SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO



CREATE PROCEDURE [rpt].[DOMO_Pac12_ASU_MensBasketball14_15_TicketSales_SeatInventory]
AS
    BEGIN

        SELECT  
				--DOMO.SEASON, DOMO.SEASON_NAME, DOMO.[EVENT], DOMO.EVENT_NAME, CAST(DOMO.[LEVEL] AS VARCHAR(32)) [LEVEL], CAST(DOMO.SECTION AS VARCHAR(32)) SECTION, CAST(DOMO.[ROW] AS VARCHAR(32)) [ROW], DOMO.SEAT, DOMO.STAT, DOMO.STAT_NAME, DOMO.ITEM,
    --            DOMO.ITEM_NAME, DOMO.I_PT, DOMO.PRICE_TYPE_NAME, DOMO.PRICE_TYPE_CLASS, DOMO.PL, DOMO.PL_NAME, DOMO.PREV_STATUS, DOMO.PREV_STATUS_NAME, DOMO.AISLE,
    --            DOMO.ORDER_DATE, DOMO.ORDER_PRICE, DOMO.CUSTOMER, DOMO.TYPE, DOMO.CUSTOMER_TYPE_NAME, DOMO.SCAN_DATE, DOMO.SCAN_TIME, DOMO.SCAN_LOC, DOMO.SCAN_CLUSTER,
    --            DOMO.SCAN_GATE, DOMO.SCAN_RESPONSE, DOMO.REDEEMED, DOMO.ATTENDED
    --          , SSBID.SSB_CRMSYSTEM_CONTACT_ID

			  CAST(DOMO.SEASON AS NVARCHAR(255)) SEASON
			, CAST(DOMO.SEASON_NAME AS NVARCHAR(255)) SEASON_NAME
			, CAST(DOMO.EVENT AS NVARCHAR(255)) EVENT
			, CAST(DOMO.EVENT_NAME AS NVARCHAR(255)) EVENT_NAME
			, CAST(DOMO.LEVEL AS NVARCHAR(255)) LEVEL
			, CAST(DOMO.SECTION AS NVARCHAR(255)) SECTION
			, CAST(DOMO.ROW AS NVARCHAR(255)) ROW
			, CAST(DOMO.SEAT AS NVARCHAR(255)) SEAT
			, CAST(DOMO.STAT AS NVARCHAR(255)) STAT
			, CAST(DOMO.STAT_NAME AS NVARCHAR(255)) STAT_NAME
			, CAST(DOMO.ITEM AS NVARCHAR(255)) ITEM
			, CAST(DOMO.ITEM_NAME AS NVARCHAR(255)) ITEM_NAME
			, CAST(DOMO.I_PT AS NVARCHAR(255)) I_PT
			, CAST(DOMO.PRICE_TYPE_NAME AS NVARCHAR(255)) PRICE_TYPE_NAME
			, CAST(DOMO.PRICE_TYPE_CLASS AS NVARCHAR(255)) PRICE_TYPE_CLASS
			, CAST(DOMO.PL AS NVARCHAR(255)) PL
			, CAST(DOMO.PL_NAME AS NVARCHAR(255)) PL_NAME
			, CAST(DOMO.PREV_STATUS AS NVARCHAR(255)) PREV_STATUS
			, CAST(DOMO.PREV_STATUS_NAME AS NVARCHAR(255)) PREV_STATUS_NAME
			, CAST(DOMO.AISLE AS NVARCHAR(255)) AISLE
			, CAST(DOMO.ORDER_DATE AS NVARCHAR(255)) ORDER_DATE
			, DOMO.ORDER_PRICE
			, CAST(DOMO.CUSTOMER AS NVARCHAR(255)) CUSTOMER
			, CAST(DOMO.TYPE AS NVARCHAR(255)) TYPE
			, CAST(DOMO.CUSTOMER_TYPE_NAME AS NVARCHAR(255)) CUSTOMER_TYPE_NAME
			, DOMO.SCAN_DATE
			, CAST(DOMO.SCAN_TIME AS NVARCHAR(255)) SCAN_TIME
			, CAST(DOMO.SCAN_LOC AS NVARCHAR(255)) SCAN_LOC
			, CAST(DOMO.SCAN_CLUSTER AS NVARCHAR(255)) SCAN_CLUSTER
			, CAST(DOMO.SCAN_GATE AS NVARCHAR(255)) SCAN_GATE
			, CAST(DOMO.SCAN_RESPONSE AS NVARCHAR(255)) SCAN_RESPONSE
			, DOMO.REDEEMED
			, CAST(DOMO.ATTENDED AS NVARCHAR(255)) ATTENDED
            , CAST(SSBID.SSB_CRMSYSTEM_CONTACT_ID AS NVARCHAR(255)) SSB_CRMSYSTEM_CONTACT_ID

        FROM    [172.31.17.15].ASU.[dbo].[DOMO_Pac12_ASU_MensBasketball14_15_TicketSales_SeatInventory] DOMO WITH (NOLOCK)
                LEFT JOIN dbo.dimcustomerssbid SSBID WITH (NOLOCK) ON SSBID.SSID = DOMO.CUSTOMER AND SSBID.SourceSystem = 'TI ASU'


    END




GO
