CREATE TABLE [bkp].[dbo__EPD_ACCOUNT_20170207]
(
[ETLSID] [varchar] (35) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[CUSTOMER] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PIN] [bigint] NULL,
[EMAIL_PREF] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LAST_USER] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[LAST_DATETIME] [datetime] NULL,
[ZID] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SOURCE_ID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXPORT_DATETIME] [datetime] NULL,
[ETL_Sync_DeltaHashKey] [binary] (32) NULL
)
GO
ALTER TABLE [bkp].[dbo__EPD_ACCOUNT_20170207] ADD CONSTRAINT [PK_EPD_ACCOUNT_eca9c3b1-9970-4bd5-a0de-36b1982a3f79] PRIMARY KEY CLUSTERED  ([ETLSID], [CUSTOMER])
GO
