CREATE TABLE [bkp].[dbo__TK_MARK_20170207]
(
[ETLSID] [varchar] (35) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[MARK] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[NAME] [varchar] (512) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LAST_USER] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[LAST_DATETIME] [datetime] NULL,
[ZID] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[SOURCE_ID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXPORT_DATETIME] [datetime] NULL,
[ETL_Sync_DeltaHashKey] [binary] (32) NULL
)
GO
ALTER TABLE [bkp].[dbo__TK_MARK_20170207] ADD CONSTRAINT [PK_TK_MARK_f0487b8d-b37e-47d4-a512-d9275d0b5e43] PRIMARY KEY CLUSTERED  ([ETLSID], [MARK])
GO
CREATE NONCLUSTERED INDEX [IDX_MARK] ON [bkp].[dbo__TK_MARK_20170207] ([MARK])
GO
