CREATE TABLE [bkp].[dbo__TK_TRANS_MP_20170207]
(
[ETLSID] [varchar] (35) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[SEASON] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[TRANS_NO] [bigint] NOT NULL,
[DATE] [datetime] NULL,
[CUSTOMER] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SALECODE] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[MP_FROM_SEASON] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[MP_FROM_TRANS_NO] [bigint] NULL,
[MP_TO_SEASON] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[MP_TO_TRANS_NO] [bigint] NULL,
[SH_OWNER_SEASON] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[SH_OWNER_TRANS_NO] [bigint] NULL,
[SH_SELLER_SEASON] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[SH_SELLER_TRANS_NO] [bigint] NULL,
[MP_BOCHG] [numeric] (18, 2) NULL,
[MP_BUY_AMT] [numeric] (18, 2) NULL,
[MP_BUY_NET] [numeric] (18, 2) NULL,
[MP_BUYER] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MP_DIFF] [numeric] (18, 2) NULL,
[MP_DMETH_TYPE] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[MP_EVENT] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[MP_NETITEM] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[MP_OWNER] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MP_QTY] [int] NULL,
[MP_SBLS] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MP_SELLCR] [numeric] (18, 2) NULL,
[MP_SELLER] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MP_SELLTIXAMT] [numeric] (18, 2) NULL,
[MP_SHPAID] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MP_SOCHG] [numeric] (18, 2) NULL,
[MP_TIXAMT] [numeric] (18, 2) NULL,
[LAST_TIME] [datetime] NULL,
[LAST_USER] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[LAST_DATETIME] [datetime] NULL,
[ZID] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[SOURCE_ID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXPORT_DATETIME] [datetime] NULL,
[ETL_Sync_DeltaHashKey] [binary] (32) NULL
)
GO
ALTER TABLE [bkp].[dbo__TK_TRANS_MP_20170207] ADD CONSTRAINT [PK_TK_TRANS_MP_2faad6cd-00d6-45c4-83bb-4838f0921591] PRIMARY KEY CLUSTERED  ([ETLSID], [SEASON], [TRANS_NO])
GO
CREATE NONCLUSTERED INDEX [IDX_CUSTOMER] ON [bkp].[dbo__TK_TRANS_MP_20170207] ([CUSTOMER])
GO
CREATE NONCLUSTERED INDEX [IDX_DATE] ON [bkp].[dbo__TK_TRANS_MP_20170207] ([DATE])
GO
CREATE NONCLUSTERED INDEX [IDX_SALECODE] ON [bkp].[dbo__TK_TRANS_MP_20170207] ([SALECODE])
GO
CREATE NONCLUSTERED INDEX [IDX_SEASON] ON [bkp].[dbo__TK_TRANS_MP_20170207] ([SEASON])
GO
CREATE NONCLUSTERED INDEX [IDX_TRANS_NO] ON [bkp].[dbo__TK_TRANS_MP_20170207] ([TRANS_NO])
GO
CREATE NONCLUSTERED INDEX [IDX_ZID] ON [bkp].[dbo__TK_TRANS_MP_20170207] ([ZID])
GO
