CREATE TABLE [bkp].[dbo__TK_TRANS_ITEM_EVENT_20170207]
(
[ETLSID] [varchar] (35) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[SEASON] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[TRANS_NO] [bigint] NOT NULL,
[VMC] [bigint] NOT NULL,
[SVMC] [bigint] NOT NULL,
[EVENT] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[E_PL] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[E_PRICE] [numeric] (18, 2) NULL,
[E_DAMT] [numeric] (18, 2) NULL,
[E_PQTY] [bigint] NULL,
[E_VQTY] [bigint] NULL,
[E_PTT_QTY] [bigint] NULL,
[E_PTF_QTY] [bigint] NULL,
[E_ITEM] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[E_OQTY] [bigint] NULL,
[E_CQTY] [bigint] NULL,
[E_OTT_QTY] [bigint] NULL,
[E_OTF_QTY] [bigint] NULL,
[E_OQTY_TOT] [bigint] NULL,
[E_PT] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[E_CPRICE] [numeric] (18, 2) NULL,
[E_FEE] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[E_FPRICE] [numeric] (18, 2) NULL,
[TOTAL_EPAY] [numeric] (18, 2) NULL,
[TOTAL_CPAY] [numeric] (18, 2) NULL,
[TOTAL_FPAY] [numeric] (18, 2) NULL,
[SALECODE] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[E_SCAMT] [numeric] (18, 2) NULL,
[TOTAL_SPAY] [numeric] (18, 2) NULL,
[DATE] [datetime] NULL,
[CUSTOMER] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ZID] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[SOURCE_ID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXPORT_DATETIME] [datetime] NULL,
[E_STAT] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ETL_Sync_DeltaHashKey] [binary] (32) NULL
)
GO
ALTER TABLE [bkp].[dbo__TK_TRANS_ITEM_EVENT_20170207] ADD CONSTRAINT [PK_TK_TRANS_ITEM_EVENT] PRIMARY KEY CLUSTERED  ([ETLSID], [SEASON], [TRANS_NO], [VMC], [SVMC])
GO
CREATE NONCLUSTERED INDEX [IDX_CUSTOMER] ON [bkp].[dbo__TK_TRANS_ITEM_EVENT_20170207] ([CUSTOMER])
GO
ALTER INDEX [IDX_CUSTOMER] ON [bkp].[dbo__TK_TRANS_ITEM_EVENT_20170207] DISABLE
GO
CREATE NONCLUSTERED INDEX [IDX_DATE] ON [bkp].[dbo__TK_TRANS_ITEM_EVENT_20170207] ([DATE])
GO
ALTER INDEX [IDX_DATE] ON [bkp].[dbo__TK_TRANS_ITEM_EVENT_20170207] DISABLE
GO
CREATE NONCLUSTERED INDEX [IDX_E_ITEM] ON [bkp].[dbo__TK_TRANS_ITEM_EVENT_20170207] ([E_ITEM])
GO
ALTER INDEX [IDX_E_ITEM] ON [bkp].[dbo__TK_TRANS_ITEM_EVENT_20170207] DISABLE
GO
CREATE NONCLUSTERED INDEX [IDX_E_PL] ON [bkp].[dbo__TK_TRANS_ITEM_EVENT_20170207] ([E_PL])
GO
ALTER INDEX [IDX_E_PL] ON [bkp].[dbo__TK_TRANS_ITEM_EVENT_20170207] DISABLE
GO
CREATE NONCLUSTERED INDEX [IDX_E_PT] ON [bkp].[dbo__TK_TRANS_ITEM_EVENT_20170207] ([E_PT])
GO
ALTER INDEX [IDX_E_PT] ON [bkp].[dbo__TK_TRANS_ITEM_EVENT_20170207] DISABLE
GO
CREATE NONCLUSTERED INDEX [IDX_EVENT] ON [bkp].[dbo__TK_TRANS_ITEM_EVENT_20170207] ([EVENT])
GO
ALTER INDEX [IDX_EVENT] ON [bkp].[dbo__TK_TRANS_ITEM_EVENT_20170207] DISABLE
GO
CREATE NONCLUSTERED INDEX [IDX_SALECODE] ON [bkp].[dbo__TK_TRANS_ITEM_EVENT_20170207] ([SALECODE])
GO
ALTER INDEX [IDX_SALECODE] ON [bkp].[dbo__TK_TRANS_ITEM_EVENT_20170207] DISABLE
GO
CREATE NONCLUSTERED INDEX [IDX_SEASON] ON [bkp].[dbo__TK_TRANS_ITEM_EVENT_20170207] ([SEASON])
GO
ALTER INDEX [IDX_SEASON] ON [bkp].[dbo__TK_TRANS_ITEM_EVENT_20170207] DISABLE
GO
CREATE NONCLUSTERED INDEX [IDX_TRANS_NO] ON [bkp].[dbo__TK_TRANS_ITEM_EVENT_20170207] ([TRANS_NO])
GO
ALTER INDEX [IDX_TRANS_NO] ON [bkp].[dbo__TK_TRANS_ITEM_EVENT_20170207] DISABLE
GO
CREATE NONCLUSTERED INDEX [IDX_VMC] ON [bkp].[dbo__TK_TRANS_ITEM_EVENT_20170207] ([VMC])
GO
ALTER INDEX [IDX_VMC] ON [bkp].[dbo__TK_TRANS_ITEM_EVENT_20170207] DISABLE
GO
CREATE NONCLUSTERED INDEX [IDX_ZID] ON [bkp].[dbo__TK_TRANS_ITEM_EVENT_20170207] ([ZID])
GO
ALTER INDEX [IDX_ZID] ON [bkp].[dbo__TK_TRANS_ITEM_EVENT_20170207] DISABLE
GO
