CREATE TABLE [bkp].[dbo__TK_TRANS_ITEM_20170207]
(
[ETLSID] [varchar] (35) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[SEASON] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[TRANS_NO] [bigint] NOT NULL,
[VMC] [bigint] NOT NULL,
[ITEM] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[I_OQTY] [bigint] NULL,
[I_CQTY] [bigint] NULL,
[I_OTT_QTY] [bigint] NULL,
[I_OTF_QTY] [bigint] NULL,
[I_OQTY_TOT] [bigint] NULL,
[I_PT] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[I_PRICE] [numeric] (18, 2) NULL,
[I_DISC] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[I_DAMT] [numeric] (18, 2) NULL,
[I_CHG] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[I_CPRICE] [numeric] (18, 2) NULL,
[I_CPAYQ] [bigint] NULL,
[I_DATE] [datetime] NULL,
[I_DISP] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[I_ACUST] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[I_BPTYPE] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[I_STOCK] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TOTAL_IPAY] [numeric] (18, 2) NULL,
[TOTAL_CPAY] [numeric] (18, 2) NULL,
[TOTAL_FPAY] [numeric] (18, 2) NULL,
[SALECODE] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[INREFSOURCE] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[INREFDATA] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[I_PROMO] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[I_SCHG] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[I_SCAMT] [numeric] (18, 2) NULL,
[TOTAL_SPAY] [numeric] (18, 2) NULL,
[I_PKG] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[DATE] [datetime] NULL,
[CUSTOMER] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[I_FPRICE] [numeric] (18, 2) NULL,
[ZID] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[SOURCE_ID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXPORT_DATETIME] [datetime] NULL,
[ETL_Sync_DeltaHashKey] [binary] (32) NULL
)
GO
ALTER TABLE [bkp].[dbo__TK_TRANS_ITEM_20170207] ADD CONSTRAINT [PK_TK_TRANS_ITEM] PRIMARY KEY CLUSTERED  ([ETLSID], [SEASON], [TRANS_NO], [VMC])
GO
CREATE NONCLUSTERED INDEX [IDX_CUSTOMER] ON [bkp].[dbo__TK_TRANS_ITEM_20170207] ([CUSTOMER])
GO
CREATE NONCLUSTERED INDEX [IDX_DATE] ON [bkp].[dbo__TK_TRANS_ITEM_20170207] ([DATE])
GO
CREATE NONCLUSTERED INDEX [IDX_I_PT] ON [bkp].[dbo__TK_TRANS_ITEM_20170207] ([I_PT])
GO
CREATE NONCLUSTERED INDEX [IDX_ITEM] ON [bkp].[dbo__TK_TRANS_ITEM_20170207] ([ITEM])
GO
CREATE NONCLUSTERED INDEX [IDX_SALECODE] ON [bkp].[dbo__TK_TRANS_ITEM_20170207] ([SALECODE])
GO
CREATE NONCLUSTERED INDEX [IDX_SEASON] ON [bkp].[dbo__TK_TRANS_ITEM_20170207] ([SEASON])
GO
CREATE NONCLUSTERED INDEX [IDX_TRANS_NO] ON [bkp].[dbo__TK_TRANS_ITEM_20170207] ([TRANS_NO])
GO
CREATE NONCLUSTERED INDEX [IDX_VMC] ON [bkp].[dbo__TK_TRANS_ITEM_20170207] ([VMC])
GO
CREATE NONCLUSTERED INDEX [IDX_ZID] ON [bkp].[dbo__TK_TRANS_ITEM_20170207] ([ZID])
GO
