CREATE TABLE [bkp].[dbo__TK_TRANS_20170207]
(
[ETLSID] [varchar] (35) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[SEASON] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[TRANS_NO] [bigint] NOT NULL,
[BATCH] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TYPE] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[REF] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DATE] [datetime] NULL,
[DOCUMENT] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CUSTOMER] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[O_AMT] [numeric] (18, 2) NULL,
[PR_AMT] [numeric] (18, 2) NULL,
[P_AMT] [numeric] (18, 2) NULL,
[R_AMT] [numeric] (18, 2) NULL,
[W_AMT] [numeric] (18, 2) NULL,
[C_AMT] [numeric] (18, 2) NULL,
[RR_AMT] [numeric] (18, 2) NULL,
[P_DATE] [datetime] NULL,
[PAYMODE] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[BALANCE] [numeric] (18, 2) NULL,
[TERMINAL_ID] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SOURCE] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[E_STAT] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[XFER_TO_SEASON] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[XFER_TO_TRANS_NO] [bigint] NULL,
[XFER_FROM_SEASON] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[XFER_FROM_TRANS_NO] [bigint] NULL,
[EXCH_OUT_SEASON] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[EXCH_OUT_TRANS_NO] [bigint] NULL,
[EXCH_IN_SEASON] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[EXCH_IN_TRANS_NO] [bigint] NULL,
[SALECODE] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[CONTROL] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[LAST_TIME] [datetime] NULL,
[LAST_USER] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[LAST_DATETIME] [datetime] NULL,
[ZID] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[SOURCE_ID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXPORT_DATETIME] [datetime] NULL,
[ETL_Sync_DeltaHashKey] [binary] (32) NULL
)
GO
ALTER TABLE [bkp].[dbo__TK_TRANS_20170207] ADD CONSTRAINT [PK_TK_TRANS] PRIMARY KEY CLUSTERED  ([ETLSID], [SEASON], [TRANS_NO])
GO
CREATE NONCLUSTERED INDEX [IDX_CUSTOMER] ON [bkp].[dbo__TK_TRANS_20170207] ([CUSTOMER])
GO
ALTER INDEX [IDX_CUSTOMER] ON [bkp].[dbo__TK_TRANS_20170207] DISABLE
GO
CREATE NONCLUSTERED INDEX [IDX_DATE] ON [bkp].[dbo__TK_TRANS_20170207] ([DATE])
GO
ALTER INDEX [IDX_DATE] ON [bkp].[dbo__TK_TRANS_20170207] DISABLE
GO
CREATE NONCLUSTERED INDEX [IDX_SALECODE] ON [bkp].[dbo__TK_TRANS_20170207] ([SALECODE])
GO
ALTER INDEX [IDX_SALECODE] ON [bkp].[dbo__TK_TRANS_20170207] DISABLE
GO
CREATE NONCLUSTERED INDEX [IDX_SEASON] ON [bkp].[dbo__TK_TRANS_20170207] ([SEASON])
GO
ALTER INDEX [IDX_SEASON] ON [bkp].[dbo__TK_TRANS_20170207] DISABLE
GO
CREATE NONCLUSTERED INDEX [IDX_TRANS_NO] ON [bkp].[dbo__TK_TRANS_20170207] ([TRANS_NO])
GO
ALTER INDEX [IDX_TRANS_NO] ON [bkp].[dbo__TK_TRANS_20170207] DISABLE
GO
CREATE NONCLUSTERED INDEX [IDX_ZID] ON [bkp].[dbo__TK_TRANS_20170207] ([ZID])
GO
ALTER INDEX [IDX_ZID] ON [bkp].[dbo__TK_TRANS_20170207] DISABLE
GO
