CREATE TABLE [bkp].[dbo__TK_SALECODE_20170207]
(
[ETLSID] [varchar] (35) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[SALECODE] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[NAME] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SCGROUP] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[LAST_USER] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[LAST_DATETIME] [datetime] NULL,
[ZID] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[SOURCE_ID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXPORT_DATETIME] [datetime] NULL,
[ETL_Sync_DeltaHashKey] [binary] (32) NULL
)
GO
ALTER TABLE [bkp].[dbo__TK_SALECODE_20170207] ADD CONSTRAINT [PK_TK_SALECODE_3dd2ff34-515f-405a-9bd6-d2e493e1e11d] PRIMARY KEY CLUSTERED  ([ETLSID], [SALECODE])
GO
CREATE NONCLUSTERED INDEX [IDX_SALECODE] ON [bkp].[dbo__TK_SALECODE_20170207] ([SALECODE])
GO
