CREATE TABLE [dbo].[TIPRICELEVELCAPACITY]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[REPORTCODE] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SEASON] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PL_CLASS] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CAPACITY] [numeric] (18, 0) NULL,
[SORT_ORDER] [int] NULL,
[INSERT_DATE] [date] NOT NULL
)
GO
ALTER TABLE [dbo].[TIPRICELEVELCAPACITY] ADD CONSTRAINT [PK_TIPRICELEVELCAPACITY] PRIMARY KEY CLUSTERED  ([ID])
GO
