CREATE TABLE [dbo].[ASU_Turnkey_Acxiom_20150828]
(
[Abilitec ID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Age 00 - 02 Female] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Age 00 - 02 Male] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Age 00 - 02 Unknown Gender] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Age 03 - 05 Female] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Age 03 - 05 Male] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Age 03 - 05 Unknown Gender] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Age 06 - 10 Female] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Age 06 - 10 Male] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Age 06 - 10 Unknown Gender] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Age 11 - 15 Female] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Age 11 - 15 Male] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Age 11 - 15 Unknown Gender] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Age 16 - 17 Female] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Age 16 - 17 Male] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Age 16 - 17 Unknown Gender] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Age in Two-Year Increments - 1st Individual] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Age in Two-Year Increments - 2nd Individual] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Age in Two-Year Increments - Input Individual] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Apartment Number] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Apparel - Female Apparel MOB's] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Apparel - Jewelry MOB's] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Apparel - Male Apparel MOB's] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Apparel - Plus Size Women's Clothing MOB's] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Apparel - Teen Fashion MOB's] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Apparel - Unknown Type] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Art & Antique MOB's] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Arts and Crafts MOB's] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Auto Supplies MOB's] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Bank Card Holder] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Bank, Financial Services - Banking] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Base Record Verification Date] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Beauty MOB's] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Book MOB's] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Business Owner] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Children's Merchandise MOB's] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Collectible MOB's] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Collectibles - Sports Memorabilia] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Computer Software MOB's] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Credit Card Holder - Unknown Type] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Discretionary Income Index] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Dwelling Type] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Education - 1st Individual] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Education - 2nd Individual] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Education - Input Individual] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Electronic MOB's] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Equestrian MOB's] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Females 18-24] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Females 25-34] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Females 35-44] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Females 45-54] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Females 55-64] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Females 65-74] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Females 75+] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Finance Company, Financial Services - Install Credit] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[First Name - 1st Individual] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[First Name - 2nd Individual] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Food MOB's] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gas Department Retail Card Holder] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gender - 1st Individual] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gender - 2nd Individual] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gender - Input Individual] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[General Gifts and Merchandise MOB's] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gift MOB's] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Health MOB's] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Home Assessed Value - Ranges] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Home Furnishing and Decorating MOB's] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Home Market Value] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Home Owner   Renter] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Home Property Type Detail] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Home Square Footage - Actual] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Home Year Built - Actual] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Household Abilitec ID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Income - Estimated Household] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InfoBase Positive Match Indicator] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Investing - Active] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Length of Residence] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Mail Order Buyer] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Mail Order Donor] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Mail Order Responder] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Males 18-24] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Males 25-34] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Males 35-44] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Males 45-54] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Males 55-64] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Males 65-74] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Males 75+] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Marital Status in the Household] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Merchandise - High Ticket Merchandise MOB's] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Merchandise - Low Ticket Merchandise MOB's] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Middle Initial - 1st Individual] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Middle Initial - 2nd Individual] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Miscellaneous, Financial Services - Insurance] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Miscellaneous, Grocery] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Miscellaneous, Miscellaneous] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Miscellaneous, TV   Mail Order Purchases] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Motorcycle Owner] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Music MOB's] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NASCAR] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Net Worth Gold] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NetWorth] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Number of Adults] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Number of Sources] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Occupation - 1st Individual] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Occupation - 2nd Individual] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Occupation - Detail - Input Individual] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Occupation - Input Individual] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Oil Company, Oil Company] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Online Purchasing Indicator] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Outdoor Gardening MOB's] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Outdoor Hunting & Fishing MOB's] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Overall Match Indicator] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PersonicX Cluster] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Personicx Cluster Code] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PersonicX Digital Cluster] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Personicx Digital Cluster Code] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Pet Supplies MOB's] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Precision Level] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Premium Card Holder] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Presence of Children] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Purchase 0 - 3 Months] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Purchase 10 - 12 Months] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Purchase 13 - 18 Months] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Purchase 19 - 24 Months] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Purchase 24+ Months] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Purchase 4 - 6 Months] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Purchase 7 - 9 Months] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Race Code] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Retail Activity Date of Last] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Retail Purchases - Most Frequent Category] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RV Owner] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Spectator Sports - Auto   Motorcycle Racing] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Spectator Sports - Baseball] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Spectator Sports - Basketball] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Spectator Sports - Football] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Spectator Sports - Hockey] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Spectator Sports - Soccer] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Spectator Sports - Tennis] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sports - Golf MOB's] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sports and Leisure - SC] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sports MOB's] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Standard Retail, Catalog Showroom   Retail Buyers] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Standard Retail, High Volume Low End Department Store Buyers] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Standard Retail, Main Street Retail] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Standard Retail, Membership Warehouse] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Standard Retail, Standard Retail] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Standard Specialty, Computer   Electronics Buyers] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Standard Specialty, Furniture Buyers] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Standard Specialty, Home Improvement] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Standard Specialty, Home Office Supply Purchases] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Standard Specialty, Specialty] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Standard Specialty, Specialty Apparel] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Standard Specialty, Sporting Goods] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Suppression - Mail - DMA] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Travel and Entertainment Card Holder] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Travel MOB's] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Truck Owner] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Unknown Gender 18-24] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Unknown Gender 25-34] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Unknown Gender 35-44] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Unknown Gender 45-54] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Unknown Gender 55-64] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Unknown Gender 65-74] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Unknown Gender 75+] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Upscale Card Holder] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Upscale Retail - High End Retail Buyers, Upscale Retail] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Upscale Specialty, Travel   Personal Services] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Vehicle - Dominant Lifestyle Indicator] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Vehicle - Known Owned Number] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Vehicle - New Car Buyer] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Vehicle - New Used Indicator - 1st Vehicle] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Vehicle - New Used Indicator - 2nd Vehicle] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Video DVD MOB's] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Working Woman] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address 1] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address 2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[City] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Country] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Email] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[First Name] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Home Phone] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Last Name] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Mobile Phone] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Person ID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Postal Code] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProspectID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[State] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Ticketing System Account ID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
