CREATE TABLE [etl].[DOMO_Pac12_ExportFile_ASU_Customer_Attribute]
(
[SSB_CRMSYSTEM_CONTACT_ID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Ticketing System Account ID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Abilitec ID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Age 00 - 02 Female] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Age 00 - 02 Male] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Age 00 - 02 Unknown Gender] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Age 03 - 05 Female] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Age 03 - 05 Male] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Age 03 - 05 Unknown Gender] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Age 06 - 10 Female] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Age 06 - 10 Male] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Age 06 - 10 Unknown Gender] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Age 11 - 15 Female] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Age 11 - 15 Male] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Age 11 - 15 Unknown Gender] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Age 16 - 17 Female] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Age 16 - 17 Male] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Age 16 - 17 Unknown Gender] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Age in Two-Year Increments - 1st Individual] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Age in Two-Year Increments - 2nd Individual] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Age in Two-Year Increments - Input Individual] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Apartment Number] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Apparel - Female Apparel MOB's] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Apparel - Jewelry MOB's] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Apparel - Male Apparel MOB's] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Apparel - Plus Size Women's Clothing MOB's] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Apparel - Teen Fashion MOB's] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Apparel - Unknown Type] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Art & Antique MOB's] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Arts and Crafts MOB's] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Auto Supplies MOB's] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Bank Card Holder] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Bank, Financial Services - Banking] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Base Record Verification Date] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Beauty MOB's] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Book MOB's] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Business Owner] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Children's Merchandise MOB's] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Collectible MOB's] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Collectibles - Sports Memorabilia] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Computer Software MOB's] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Credit Card Holder - Unknown Type] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Discretionary Income Index] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Dwelling Type] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Education - 1st Individual] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Education - 2nd Individual] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Education - Input Individual] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Electronic MOB's] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Equestrian MOB's] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Females 18-24] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Females 25-34] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Females 35-44] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Females 45-54] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Females 55-64] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Females 65-74] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Females 75+] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Finance Company, Financial Services - Install Credit] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[First Name - 1st Individual] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[First Name - 2nd Individual] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Food MOB's] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gas Department Retail Card Holder] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gender - 1st Individual] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gender - 2nd Individual] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gender - Input Individual] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[General Gifts and Merchandise MOB's] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gift MOB's] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Health MOB's] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Home Assessed Value - Ranges] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Home Furnishing and Decorating MOB's] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Home Market Value] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Home Owner   Renter] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Home Phone] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Home Property Type Detail] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Home Square Footage - Actual] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Home Year Built - Actual] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Income - Estimated Household] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InfoBase Positive Match Indicator] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Investing - Active] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Length of Residence] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Mail Order Buyer] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Mail Order Donor] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Mail Order Responder] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Males 18-24] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Males 25-34] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Males 35-44] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Males 45-54] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Males 55-64] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Males 65-74] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Males 75+] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Marital Status in the Household] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Merchandise - High Ticket Merchandise MOB's] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Merchandise - Low Ticket Merchandise MOB's] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Middle Initial - 1st Individual] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Middle Initial - 2nd Individual] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Miscellaneous, Financial Services - Insurance] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Miscellaneous, Grocery] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Miscellaneous, Miscellaneous] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Miscellaneous, TV   Mail Order Purchases] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Motorcycle Owner] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Music MOB's] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Net Worth Gold] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Number of Adults] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Number of Sources] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Occupation - 1st Individual] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Occupation - 2nd Individual] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Occupation - Detail - Input Individual] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Occupation - Input Individual] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Oil Company, Oil Company] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Online Purchasing Indicator] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Outdoor Gardening MOB's] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Outdoor Hunting & Fishing MOB's] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Overall Match Indicator] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Personicx Cluster Code] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PersonicX Cluster] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Personicx Digital Cluster Code] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PersonicX Digital Cluster] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Pet Supplies MOB's] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Precision Level] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Premium Card Holder] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Presence of Children] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Purchase 0 - 3 Months] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Purchase 10 - 12 Months] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Purchase 13 - 18 Months] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Purchase 19 - 24 Months] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Purchase 24+ Months] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Purchase 4 - 6 Months] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Purchase 7 - 9 Months] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Race Code] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Retail Activity Date of Last] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Retail Purchases - Most Frequent Category] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RV Owner] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Spectator Sports - Auto   Motorcycle Racing] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Spectator Sports - Baseball] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Spectator Sports - Basketball] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Spectator Sports - Football] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Spectator Sports - Hockey] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Spectator Sports - Soccer] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Spectator Sports - Tennis] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sports - Golf MOB's] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sports and Leisure - SC] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sports MOB's] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Standard Retail, Catalog Showroom   Retail Buyers] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Standard Retail, High Volume Low End Department Store Buyers] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Standard Retail, Main Street Retail] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Standard Retail, Membership Warehouse] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Standard Retail, Standard Retail] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Standard Specialty, Computer   Electronics Buyers] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Standard Specialty, Furniture Buyers] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Standard Specialty, Home Improvement] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Standard Specialty, Home Office Supply Purchases] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Standard Specialty, Specialty] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Standard Specialty, Specialty Apparel] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Standard Specialty, Sporting Goods] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Suppression - Mail - DMA] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Travel and Entertainment Card Holder] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Travel MOB's] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Truck Owner] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Unknown Gender 18-24] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Unknown Gender 25-34] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Unknown Gender 35-44] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Unknown Gender 45-54] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Unknown Gender 55-64] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Unknown Gender 65-74] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Unknown Gender 75+] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Upscale Card Holder] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Upscale Retail - High End Retail Buyers, Upscale Retail] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Upscale Specialty, Travel   Personal Services] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Vehicle - Dominant Lifestyle Indicator] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Vehicle - Known Owned Number] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Vehicle - New Car Buyer] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Vehicle - New Used Indicator - 1st Vehicle] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Vehicle - New Used Indicator - 2nd Vehicle] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Video DVD MOB's] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Working Woman] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FootballCapacity] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FootballCapacityDate] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FootballPriority] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FootballPriorityDate] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BasketballCapacity] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BasketballCapacityDate] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BasketballPriority] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BasketballPriorityDate] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BaseballCapacity] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BaseballCapacityDate] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BaseballPriority] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BaseballPriorityDate] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Abilitec ID Append Date] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Turnkey Standard Bundle Date] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PriorityPoints] [float] NULL,
[PriorityPointsRank] [int] NULL,
[GIFT_CLUB_DESC_PY] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[QUALIFIED_AMOUNT_PY] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GIFT_CLUB_DESC_CY] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[QUALIFIED_AMOUNT_CY] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GIFT_CLUB_DESC_FutureYears] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[QUALIFIED_AMOUNT_FutureYears] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
