CREATE TABLE [rpt].[TM_PRICELEVELCAPACITY]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[Sport] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SeasonYear] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PL_CLASS] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CAPACITY] [numeric] (18, 0) NULL,
[SORT_ORDER] [int] NULL,
[INSERT_DATE] [date] NOT NULL
)
GO
ALTER TABLE [rpt].[TM_PRICELEVELCAPACITY] ADD CONSTRAINT [PK_TMPRICELEVELCAPACITY] PRIMARY KEY CLUSTERED  ([ID])
GO
