CREATE TABLE [src].[Sync_TI_TK_TRANS_MP]
(
[ETLSID] [varchar] (35) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[SEASON] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[TRANS_NO] [bigint] NOT NULL,
[DATE] [datetime] NULL,
[CUSTOMER] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SALECODE] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[MP_FROM_SEASON] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[MP_FROM_TRANS_NO] [bigint] NULL,
[MP_TO_SEASON] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[MP_TO_TRANS_NO] [bigint] NULL,
[SH_OWNER_SEASON] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[SH_OWNER_TRANS_NO] [bigint] NULL,
[SH_SELLER_SEASON] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[SH_SELLER_TRANS_NO] [bigint] NULL,
[MP_BOCHG] [numeric] (18, 2) NULL,
[MP_BUY_AMT] [numeric] (18, 2) NULL,
[MP_BUY_NET] [numeric] (18, 2) NULL,
[MP_BUYER] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MP_DIFF] [numeric] (18, 2) NULL,
[MP_DMETH_TYPE] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[MP_EVENT] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[MP_NETITEM] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[MP_OWNER] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MP_QTY] [int] NULL,
[MP_SBLS] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MP_SELLCR] [numeric] (18, 2) NULL,
[MP_SELLER] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MP_SELLTIXAMT] [numeric] (18, 2) NULL,
[MP_SHPAID] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MP_SOCHG] [numeric] (18, 2) NULL,
[MP_TIXAMT] [numeric] (18, 2) NULL,
[MP_PL] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[LAST_TIME] [datetime] NULL,
[LAST_USER] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[LAST_DATETIME] [datetime] NULL,
[ZID] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[SOURCE_ID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXPORT_DATETIME] [datetime] NULL,
[ETL_Sync_Id] [int] NOT NULL IDENTITY(1, 1)
)
GO
ALTER TABLE [src].[Sync_TI_TK_TRANS_MP] ADD CONSTRAINT [PK__Sync_TI___19364FD2AA5885C5] PRIMARY KEY CLUSTERED  ([ETL_Sync_Id])
GO
