CREATE TABLE [src].[Sync_TI_TK_PTABLE_PRLEV_DEL]
(
[SEASON] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[PTABLE] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[PL] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[ETL_Sync_Id] [int] NOT NULL IDENTITY(1, 1)
)
GO
ALTER TABLE [src].[Sync_TI_TK_PTABLE_PRLEV_DEL] ADD CONSTRAINT [PK__Sync_TI___19364FD2EC3A8640] PRIMARY KEY CLUSTERED  ([ETL_Sync_Id])
GO
