CREATE TABLE [src].[Sync_TI_TK_TRANS_ITEM_EVENT_PAYMODE_DEL]
(
[SEASON] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[TRANS_NO] [bigint] NOT NULL,
[VMC] [bigint] NOT NULL,
[SVMC] [bigint] NOT NULL,
[SSVMC] [bigint] NOT NULL,
[ETL_Sync_Id] [int] NOT NULL IDENTITY(1, 1)
)
GO
ALTER TABLE [src].[Sync_TI_TK_TRANS_ITEM_EVENT_PAYMODE_DEL] ADD CONSTRAINT [PK__Sync_TI___19364FD238402A4B] PRIMARY KEY CLUSTERED  ([ETL_Sync_Id])
GO
