CREATE TABLE [src].[Sync_TI_PD_ADDRESS_DEL]
(
[PATRON] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ADTYPE] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[ETL_Sync_Id] [int] NOT NULL IDENTITY(1, 1)
)
GO
ALTER TABLE [src].[Sync_TI_PD_ADDRESS_DEL] ADD CONSTRAINT [PK__Sync_TI___19364FD26D2A6406] PRIMARY KEY CLUSTERED  ([ETL_Sync_Id])
GO
