CREATE TABLE [src].[Sync_TI_TK_PRTYPE_DEL]
(
[SEASON] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[PRTYPE] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[ETL_Sync_Id] [int] NOT NULL IDENTITY(1, 1)
)
GO
ALTER TABLE [src].[Sync_TI_TK_PRTYPE_DEL] ADD CONSTRAINT [PK__Sync_TI___19364FD28CD4BD2B] PRIMARY KEY CLUSTERED  ([ETL_Sync_Id])
GO
