CREATE TABLE [src].[Sync_TI_PD_PATRON_PHONE_TYPE]
(
[ETLSID] [varchar] (35) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[PATRON] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[VMC] [bigint] NOT NULL,
[PHONE] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PHONE_TYPE] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[ZID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SOURCE_ID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXPORT_DATETIME] [datetime] NULL,
[ETL_Sync_Id] [int] NOT NULL IDENTITY(1, 1)
)
GO
ALTER TABLE [src].[Sync_TI_PD_PATRON_PHONE_TYPE] ADD CONSTRAINT [PK__Sync_TI___19364FD29BF16E45] PRIMARY KEY CLUSTERED  ([ETL_Sync_Id])
GO
