CREATE TABLE [src].[Sync_TI_PD_PATRON_SAL_TYPE]
(
[ETL_Sync_Id] [int] NOT NULL IDENTITY(1, 1),
[ETLSID] [varchar] (35) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[PATRON] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[VMC] [bigint] NOT NULL,
[SAL_TYPE] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[SALUTATION] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[ZID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[SOURCE_ID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[EXPORT_DATETIME] [datetime] NULL
)
GO
ALTER TABLE [src].[Sync_TI_PD_PATRON_SAL_TYPE] ADD CONSTRAINT [PK__Sync_TI___19364FD2D5761C2F] PRIMARY KEY CLUSTERED  ([ETL_Sync_Id])
GO
