CREATE TABLE [src].[Sync_TI_PD_PATRON_ATTRIBUTE]
(
[ETL_Sync_Id] [int] NOT NULL IDENTITY(1, 1),
[ETLSID] [varchar] (35) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[PATRON] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[VMC] [bigint] NOT NULL,
[ATTRIBUTE] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[NOTE] [varchar] (512) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[ATTRIBUTE_SOURCE] [bigint] NULL,
[ZID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[SOURCE_ID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[EXPORT_DATETIME] [datetime] NULL
)
GO
ALTER TABLE [src].[Sync_TI_PD_PATRON_ATTRIBUTE] ADD CONSTRAINT [PK__Sync_TI___19364FD2E37BBA21] PRIMARY KEY CLUSTERED  ([ETL_Sync_Id])
GO
