CREATE TABLE [src].[Sync_TI_TK_TRANS_ITEM_EVENT]
(
[ETLSID] [varchar] (35) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[SEASON] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[TRANS_NO] [bigint] NOT NULL,
[VMC] [bigint] NOT NULL,
[SVMC] [bigint] NOT NULL,
[EVENT] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[E_PL] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[E_PRICE] [numeric] (18, 2) NULL,
[E_DAMT] [numeric] (18, 2) NULL,
[E_PQTY] [bigint] NULL,
[E_VQTY] [bigint] NULL,
[E_PTT_QTY] [bigint] NULL,
[E_PTF_QTY] [bigint] NULL,
[E_ITEM] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[E_OQTY] [bigint] NULL,
[E_CQTY] [bigint] NULL,
[E_OTT_QTY] [bigint] NULL,
[E_OTF_QTY] [bigint] NULL,
[E_OQTY_TOT] [bigint] NULL,
[E_PT] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[E_STAT] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[E_QTY] [bigint] NULL,
[E_CPRICE] [numeric] (18, 2) NULL,
[E_FEE] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[E_FPRICE] [numeric] (18, 2) NULL,
[TOTAL_EPAY] [numeric] (18, 2) NULL,
[TOTAL_CPAY] [numeric] (18, 2) NULL,
[TOTAL_FPAY] [numeric] (18, 2) NULL,
[SALECODE] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[E_SCAMT] [numeric] (18, 2) NULL,
[TOTAL_SPAY] [numeric] (18, 2) NULL,
[DATE] [datetime] NULL,
[CUSTOMER] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ZID] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[SOURCE_ID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXPORT_DATETIME] [datetime] NULL,
[ETL_Sync_Id] [int] NOT NULL IDENTITY(1, 1)
)
GO
ALTER TABLE [src].[Sync_TI_TK_TRANS_ITEM_EVENT] ADD CONSTRAINT [PK__Sync_TI___19364FD23E002731] PRIMARY KEY CLUSTERED  ([ETL_Sync_Id])
GO
