CREATE TABLE [src].[Sync_TI_TK_BC_DEL]
(
[BC_ID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[ETL_Sync_Id] [int] NOT NULL IDENTITY(1, 1)
)
GO
ALTER TABLE [src].[Sync_TI_TK_BC_DEL] ADD CONSTRAINT [PK__Sync_TI___19364FD230A055F8] PRIMARY KEY CLUSTERED  ([ETL_Sync_Id])
GO
