CREATE TABLE [src].[Sync_TI_TK_SSTAT_DEL]
(
[SEASON] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[SSTAT] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[ETL_Sync_Id] [int] NOT NULL IDENTITY(1, 1)
)
GO
ALTER TABLE [src].[Sync_TI_TK_SSTAT_DEL] ADD CONSTRAINT [PK__Sync_TI___19364FD2C823C1CB] PRIMARY KEY CLUSTERED  ([ETL_Sync_Id])
GO
