CREATE TABLE [ssb].[CI_Seasons]
(
[Id] [int] NOT NULL IDENTITY(1, 1),
[SEASON] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL
)
GO
ALTER TABLE [ssb].[CI_Seasons] ADD CONSTRAINT [PK__CI_Seaso__3214EC071E3BCF40] PRIMARY KEY CLUSTERED  ([Id])
GO
